export const signup = async (req, res) => {
  try {
    
  } catch (error) {
    res.status(500).json({ error: "Internal server error" });
    console.log(error);
  }
};
